version: '3.4'

services:
  app:
    build: .
    ports:
      - "8088:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - weaviate
    command: >
      bash -c "
        echo 'Waiting for Weaviate to start...' &&
        sleep 15 &&
        echo 'Running database setup...' &&
        python src/utils/setup_db.py &&
        echo 'Starting FastAPI application...' &&
        uvicorn src.app:app --host 0.0.0.0 --port 8000
      "
    networks:
      - weaviate_net

  weaviate:
    image: semitechnologies/weaviate:1.21.5
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - weaviate_net

networks:
  weaviate_net:
    driver: bridge

volumes:
  weaviate_data: 
