version: '3.8'

services:
  app:
    build: .
    ports:
      - "8088:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - MODEL_NAME=gpt-3.5-turbo
      - COLLECTION_NAME=SupportDocs
      - MAX_CONTEXT_DOCS=3
      - TEMPERATURE=0.7
      - MAX_TOKENS=300
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:1.21.3
    ports:
      - "8087:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: 
